# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0

[versions]
avro = "1.12.1"
avroPlugin = "1.9.1"
dependencyManagement = "1.1.7"
kotlin = "2.3.10"
kotlinLogging = "8.0.01"
mockk = "1.14.9"
msal4j = "1.24.0"
sonarqube = "7.2.2.6593"
spotless = "8.2.1"
springBoot = "4.0.2"
springmockk = "5.0.1"

[libraries]
assertJ = { group = "org.assertj", name = "assertj-core" }
avro = { group = "org.apache.avro", name = "avro", version.ref = "avro" }
junitJupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher" }
kafkaClients = { group = "org.apache.kafka", name = "kafka-clients" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
msal = { group = "com.microsoft.azure", name = "msal4j", version.ref = "msal4j" }
slf4jApi = { group = "org.slf4j", name = "slf4j-api" }
kotlinReflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlinLoggingJvm = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlinLogging" }
springBoot = { group = "org.springframework.boot", name = "spring-boot" }
springBootConfigurationProcessor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }
springBootDependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springBoot" }
springBootStarter = { group = "org.springframework.boot", name = "spring-boot-starter" }
springBootStarterTest = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
springBootTest = { group = "org.springframework.boot", name = "spring-boot-test" }
springContext = { group = "org.springframework", name = "spring-context" }
springBootKafka = { group = "org.springframework.boot", name = "spring-boot-starter-kafka" }
springBootKafkaTest = { group = "org.springframework.boot", name = "spring-boot-starter-kafka-test" }
springmockk = { group = "com.ninja-squad", name = "springmockk", version.ref = "springmockk" }
springTest = { group = "org.springframework", name = "spring-test" }

[plugins]
avro = { id = "com.github.davidmc24.gradle.plugin.avro", version.ref = "avroPlugin" }
dependencyManagement = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
jacoco = { id = "jacoco" }
jacocoReportAggregation = { id = "jacoco-report-aggregation" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
mavenPublish = { id = "org.gradle.maven-publish" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
