name: Gradle Pipeline

on:
  push:
    branches: [ "main" , "develop" ]
    tags: [ "v**" ]
  pull_request:
    branches: [ "main", "develop"  ]

jobs:
  build:
    runs-on: [ self-hosted, X64, Linux, default ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and publish with Gradle
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: build
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Maven artifacts
        if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
